# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
references:
  config: &config
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/nuxt-ci-sample
jobs:
  test:
    <<: *config
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  build:
    <<: *config
    steps:
      - checkout
      - run: yarn build
