# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  test_and_deploy:
    jobs:
      - build
      - deploy:
          context: Netlify
          requires:
            - build
          filters:
            branches:
              only:
                - master
jobs:
  build:
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/nuxt-ci-sample
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn build
  deploy:
    docker:
      - image: circleci/node:12.14.0
    working_directory: ~/nuxt-ci-sample
    steps:
      - checkout
      - run: yarn deploy --prod -d dist -a ${NETLIFY_AUTH_TOKEN} -s ${NETLIFY_SITE_ID}
